project_name: latinasub
builds:
  - id: main
    main: ./cmd/latinasub
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64_v1
      - linux_arm64
      - linux_arm_7
      - windows_amd64_v1
      - darwin_amd64_v1
    mod_timestamp: '{{ .CommitTimestamp }}'
snapshot:
  name_template: "{{ .Version }}.{{ .ShortCommit }}"
release:
  github:
    owner: LalatinaHub
    name: latinasub
  draft: true
  prerelease: auto
  mode: replace
  skip_upload: false
